# Copyright 2021-2023 Nordcloud Oy or its affiliates. All Rights Reserved.

name: Lint
on:
  pull_request:
    branches: [master]
jobs:
  lint_check:
    name: Run ESLint on local test files
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: package.json

      - run: npm ci
      - run: npm audit signatures
      - run: npm run lint
